sqlite:
  :adapter: sqlite
  :dbfile: smartguard_test.sqlite.db
sqlite3:
  :adapter: sqlite3
  :dbfile: smartguard_test.sqlite3.db
postgresql:
  :adapter: postgresql
  :username: rst
  :password: rstgrumble
  :database: smartguard_test
  :min_messages: ERROR
mysql:
  :adapter: mysql
  :host: localhost
  :username: rails
  :password:
  :database: smartguard_test
oracle:
  :adapter: oracle
  :username: rails_rst_test
  :password: rails_rst_test
  :database: SL3_DEMO
